# Generated by Django 2.2.13 on 2022-06-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20220624_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
