# Generated by Django 2.2.13 on 2022-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soled',
            field=models.IntegerField(default=0),
        ),
    ]
