# Generated by Django 2.2.13 on 2022-07-24 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0010_auto_20220722_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentModel',
        ),
    ]
