# Generated by Django 2.2.13 on 2022-07-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_auto_20220726_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
