# Generated by Django 2.2.13 on 2022-08-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='ordered',
        ),
    ]
