# Generated by Django 2.2.13 on 2022-08-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_auto_20220811_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='ordered_status',
        ),
    ]
