# Generated by Django 2.2.13 on 2022-08-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_auto_20220811_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_status',
            new_name='ordered',
        ),
    ]
